except OSError:. raise RuntimeError from None. Traceback (most recent call last): File "<stdin>", line 4, in <module> raise RuntimeError from None RuntimeError Exception try >>> try:. raise KeyboardInterrupt. finally:. print('Goodbye, world. '). Goodbye, world. Traceback (most recent call last): File "<stdin>", line 2, in <module> raise KeyboardInterrupt KeyboardInterrupt finally finally try finally try try except except finally except else finally finally break continue return try break continue return finally break continue return finally return finally return try return >>> def bool_return():. try:. return True. finally:. return False. >>> bool_return() False >>> def divide(x, y):. try:. result = x / y. except ZeroDivisionError:. print("division by zero. "). else:. print("result is", result). finally:. print("executing finally clause"). >>> divide(2, 1) result is 2. 0 executing finally clause >>> divide(2, 0) division by zero. executing finally clause >>> divide("2", "1") executing finally clause Traceback (most recent call last): File "<stdin>", line 1, in <module> divide("2", "1") ~~~~~~^^^^^^^^^^ File "<stdin>", line 3, in divide result = x / y ~~^~~ TypeError: unsupported operand type(s) for /: 'str' and 'str' finally TypeError except finally finally for line in open("myfile. txt"): print(line, end="") with with open("myfile. txt") as f: for line in f: print(line, end="") ExceptionGroup >>> def f():. excs = [OSError('error 1'), SystemError('error 2')]. raise ExceptionGroup('there were problems', excs). >>> f() + Exception Group Traceback (most recent call last): | File "<stdin>", line 1, in <module> | f() | ~^^ | File "<stdin>", line 3, in f | raise ExceptionGroup('there were problems', excs) | ExceptionGroup: there were problems (2 sub-exceptions) +-+---------------- 1 ---------------- | OSError: error 1 +---------------- 2 ---------------- | SystemError: error 2 +------------------------------------ >>> try:. f(). except Exception as e:. print(f'caught {type(e)}: e').