error and mmap. error have been merged into OSError, and the constructor may return a subclass. EnvironmentError IOError WindowsError socket. error select. error mmap. error OSError Changed in version 3. 4: The filename attribute is now the original file name passed to the function, instead of the name encoded to or decoded from the filesystem encoding and error handler. Also, the filename2 constructor argument and attribute was added. filename Raised when the result of an arithmetic operation is too large to be represented. This cannot occur for integers (which would rather raise MemoryError than give up). However, for historical reasons, OverflowError is sometimes raised for integers that are outside a required range. Because of the lack of standardization of floating-point exception handling in C, most floating-point operations are not checked. MemoryError This exception is derived from RuntimeError. It is raised when an operation is blocked during interpreter shutdown also known as Python finalization. RuntimeError Examples of operations which can be blocked with a PythonFinalizationError during the Python finalization: PythonFinalizationError Creating a new Python thread. Creating a new Python thread. os. fork(). os. fork(). os. fork() See also the sys. is_finalizing() function. sys. is_finalizing() Added in version 3. 13: Previously, a plain RuntimeError was raised. RuntimeError This exception is derived from RuntimeError. It is raised when the interpreter detects that the maximum recursion depth (see sys. getrecursionlimit()) is exceeded. RuntimeError sys. getrecursionlimit() Added in version 3. 5: Previously, a plain RuntimeError was raised. RuntimeError This exception is raised when a weak reference proxy, created by the weakref. proxy() function, is used to access an attribute of the referent after it has been garbage collected. For more information on weak references, see the weakref module. weakref. proxy() weakref Raised when an error is detected that doesnâ€™t fall in any of the other categories. The associated value is a string indicating what precisely went wrong. Raised by built-in function next() and an iterator's next() method to signal that there are no further items produced by the iterator. next() __next__() The exception object has a single attribute value, which is given as an argument when constructing the exception, and defaults to None.