relative_to('/usr') Traceback (most recent call last): File "<stdin>", line 1, in <module> File "pathlib. py", line 941, in relative_to raise ValueError(error_message. format(str(self), str(formatted))) ValueError: '/etc/passwd' is not in the subpath of '/usr' OR one path is relative and the other is absolute. When walk_up is false (the default), the path must start with other. When the argument is true,. entries may be added to form the relative path. In all other cases, such as the paths referencing different drives, ValueError is raised. :. ValueError >>> p. relative_to('/usr', walk_up=True) PurePosixPath('. /etc/passwd') >>> p. relative_to('foo', walk_up=True) Traceback (most recent call last): File "<stdin>", line 1, in <module> File "pathlib. py", line 941, in relative_to raise ValueError(error_message. format(str(self), str(formatted))) ValueError: '/etc/passwd' is not on the same drive as 'foo' OR one path is relative and the other is absolute. Warning This function is part of PurePath and works with strings. It does not check or access the underlying file structure. This can impact the walk_up option as it assumes that no symlinks are present in the path; call resolve() first if necessary to resolve symlinks. PurePath resolve() Changed in version 3. 12: The walk_up parameter was added (old behavior is the same as walk_up=False). walk_up=False Deprecated since version 3. 12, will be removed in version 3. 14: Passing additional positional arguments is deprecated; if supplied, they are joined with other. Return a new path with the name changed. If the original path doesnâ€™t have a name, ValueError is raised: name >>> p = PureWindowsPath('c:/Downloads/pathlib. tar. gz') >>> p. with_name('setup. py') PureWindowsPath('c:/Downloads/setup. py') >>> p = PureWindowsPath('c:/') >>> p. with_name('setup. py') Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/antoine/cpython/default/Lib/pathlib.